language: node_js
node_js:
  - "0.12"
#  - "0.11"
#  - "0.10"
#  - "0.8"
#  - "0.6"
#  - "iojs"
#  - "iojs-v1.0.4" 
#bundler_args: --retry 2
#sudo: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
#install: travis_wait npm install
